[package]
name = "file_open_core-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-ebpf = { git = "https://github.com/aya-rs/aya" }
aya-log-ebpf = { git = "https://github.com/aya-rs/aya" }
file_open_core-common = { path = "../file_open_core-common" }

[build-dependencies]
aya-tool = { git = "https://github.com/deepfence/aya-rs", rev = "e5d107d" }

[[bin]]
name = "file_open_core"
path = "src/main.rs"

[profile.dev]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[workspace]
members = []
